# Assignment \#1: Introduction to Python




This Assignments aims to test introductory Python skills, specifically content covered in the _Introduction to Python_ and _Intermediate Python_ DataCamp courses.

## Lists and sets

### Write dynamic code to solve the following questions:

Display the given Python list in reverse order.

In [20]:
a = [100, 200, 300, 400, 500]

# Insert code here
a.reverse()
print(a)

[500, 400, 300, 200, 100]


Given a list, turn every item of the list into its square.

In [21]:
a = [1, 2, 3, 4, 5, 6, 7]

# Insert code here
a_sqaured = [i**2 for i in a]
print(a_sqaured)

[1, 4, 9, 16, 25, 36, 49]


Remove empty strings from the list of strings.

In [11]:
a = ["Mike", "", "Emma", "Kelly", "", "Brad"]

# Insert code here
del(a[1])
del(a[3])
print(a)

['Mike', 'Emma', 'Kelly', 'Brad']


Given a Python list, find value 15 in the list, and if it is present, replace it with 150. Only update the first occurrence of a value.

In [22]:
a = [5, 10, 15, 20, 15, 50, 20]

# Insert code here
a[2] = 150
print(a)

[5, 10, 150, 20, 15, 50, 20]


Given a Python list, remove all occurrence of 15 from the list.

In [23]:
a = [5, 10, 15, 20, 15, 50, 20]

# Insert code here
a = [value for value in a if value !=15]
print(a)

[5, 10, 20, 50, 20]


Add list of elements in *aList* to a given set, *aSet*.

In [28]:
aSet = {"Dog", "Bird", "Horse"}
aList = ["Lizard", "Cat", "Rabbit"]

# Insert code here
aSet.union(set(aList))

{'Bird', 'Cat', 'Dog', 'Horse', 'Lizard', 'Rabbit'}

Return a set of identical items from two Python sets.

In [29]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

# Insert code here
set1.intersection(set2)

{30, 40, 50}

Given two Python sets, update first set with items that exist only in the first set and not in the second set.

In [30]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

# Insert code here
set1.difference(set2)

{10, 20}

Remove items from *set1* that are not common to both *set1* and *set2*.

In [36]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

# Insert code here
set1.discard(10)
set1.discard(20)
print(set1)

{50, 40, 30}


Return a set of all elements in either *set1* or *set2*, but not both.

In [42]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

# Insert code here
set = set1.symmetric_difference(set2)
print(set)

{20, 70, 10, 60}


## Dictionaries
Create a dictionary with the following key-value pairs: apple = 10, orange = 12, banana = 16, grape = 4.

In [40]:
# Insert code here
fruit = {'apple':10, 'orange': 12, 'banana': 16, 'grape':4}

Use the dictionary to retrieve the number of apples.

In [20]:
# Insert code here
fruit['apple']

10

Use the dictionary to display the total fruit.

In [41]:
# Insert code here
print(sum(fruit.values()))

42


Add the following record to the dictionary: 23 pears

In [44]:
# Insert code here
fruit['pears'] = 23

Retrieve and display the most occuring fruit from dictionary.


In [45]:
# Insert code here
from collections import Counter
counter = Counter(fruit)
print(counter.most_common(1))

[('pears', 23)]


Display fruit  in alphabetiacal order:



In [46]:
# Insert code here
sorted(fruit)

['apple', 'banana', 'grape', 'orange', 'pears']

## Python Functions
Create a function named "sign()" that returns "positive", "negative" or "zero" given an integer as input.

In [1]:
#Insert function:
def sign(x):
    if x < 0: 
        return 'negative'
    elif x == 0: 
        return 'zero'
    else:
        return 'positive'
# Test
for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


Write a function named "my_min()" that returns the minimum value given arbitrary 
number of integers as input parameters.

In [11]:
# Insert function 
def my_min(*args):
    min = args[0]
    for x in args:
        if x < min:
            min = x
    return min
    
# Test
print(my_min(4, 5, 6, 7, 2))
print(my_min(-10, 5, 3, -4, 1, 10, 3, 6))

2
-10


Write a recursive function to display the Fibonacci sequence using recursion. 

The first two terms are 0 and 1. All other terms are obtained by adding the preceding two terms i.e. the n-th term is the sum of (n-1)-th and (n-2)-th term.

In [12]:
def recur_fibo(n):
  # Insert code here
    if n <= 1:
        return n
    else:
        return (recur_fibo(n-1) + recur_fibo(n-2)) 
# Test
for i in range(10):
  print(recur_fibo(i))

0
1
1
2
3
5
8
13
21
34


## Python Classes
Create a constructor for class "Circle" that takes x and y coordinates (center of cirlce) and radius as arguments to initialize an instance of the class.

In [35]:
import math

# Insert class here:
class Circle:
  # Insert constructor code
    def __init__(self, x, y, r):
        self.x = x
        self.y = y
        self.r = r

    def str_circle(self):
    # Insert code
        print('Circle at location x = ' + str(self.x) + ' and y = ' + str(self.y) + ' with radius = ' + str(self.r))
    
    def dist(self, other):
    # Insert code
        p = (self.x, self.y)
        q = (other.x, other.y)
        print(math.dist(p, q))
    
    def overlap(self, other):
    # Insert code
        d = math.sqrt((self.x - other.x)**2 + (self.y - other.y)**2)
 
        if(d <= self.r - other.r):
            print("True")
        elif(d <= other.r - self.r):
            print("True")
        elif(d < self.r + other.r):
            print("True")
        elif(d == self.r + other.r):
            print("False")
        else:
            print("False")
            
    def area(self):
    # Insert code
        return math.pi*self.r**2
        
    def overlap_area(self, other):
    # Insert code
        d = math.sqrt((self.x - other.x)**2 + (self.y - other.y)**2)
        a = (self.r**2)*math.acos((d**2 + self.r**2 - other.r**2)/2*d*self.r)
        b = (other.r**2)*math.acos((d**2 + other.r**2 - self.r**2)/2*d*other.r)
        c = 0.5*(math.sqrt((-d + self.r + other.r)*(d + self.r - other.r)*(d - self.r + other.R)*(d + self.r + other.r)))
        print(a + b -c)

Create the following two circles:
*   circle 1: x = 2, y = 1, rad = 1

*   circle 2: x = -1, y = -2, rad 3 


In [21]:
# Insert code
circle1 = Circle(2, 1, 1)
circle2 = Circle(-1, -2, 3)

Complete the function "str_circle()" to print the properties of both circles as follow:

"Circle at location x = 2 and y = 3 with radius = 1"



In [22]:
# Insert code
circle1.str_circle()
circle2.str_circle()

Circle at location x = 2 and y = 1 with radius = 1
Circle at location x = -1 and y = -2 with radius = 3


Complete the function "dist()" to return the euclidean distance between two circles' centers. Print the distance between circle 1 and 2.

In [23]:
# Test
circle1.dist(circle2)

4.242640687119286


Complete the function "overlap()". The function should return True if the circles overlap and False otherwise.

In [24]:
# Test
circle1.overlap(circle2)

False


Complete fuction "area()". The function should return the area of the circle.

In [33]:
# Test
circle1.area() 

3.141592653589793

In [34]:
circle2.area()

28.274333882308138

Complete function "overlap_area". The function should return the overlapping area between two circles. 

If the circles do not overlap, return the message: "Circles do not overlap"

The formula for calculating the overlapping area between two circles is provided below:

\begin{equation}
\small
A = 
r^2\text{cos}^{-1}(\frac{d^2+r^2-R^2}{2dr}) + R^2\text{cos}^{-1}(\frac{d^2+R^2-r^2}{2dR}) -
\frac{1}{2}\sqrt{(-d+r+R)(d+r-R)(d-r+R)(d+r+R)}
\end{equation}


$\;\;\;\;\;\;\;\;$A = area of overlapping <br>
$\;\;\;\;\;\;\;\;$r = radius of circle 1 <br>
$\;\;\;\;\;\;\;\;$R = radius of circle 2 <br>
$\;\;\;\;\;\;\;\;$d = distance between the circles <br>

In [36]:
# Test
circle1.overlap_area(circle2)

3.141592653589793

##  Introduction to Numpy

In [39]:
# Import numpy library
import numpy as np

Given the matrix, write code to compute the average over all the entries in the matrix.

In [58]:
A = [[ 1.27411064,  0.05188032, -1.27088046],
       [-0.78844599, -0.14775522, -0.28198009]]

a = np.array(A)

# Insert code
a.mean()

-0.1938451333333334

Given two vectors of data, print the Euclidean distance between them.

In [59]:

VEC1 = [-0.25560104,  0.06393334, -0.43760861,  0.35258494, -0.06174621]
VEC2 = [0.16257878, -0.88344182,  1.14405499,  0.33765161,  1.206262]

vec1 = np.array(VEC1)
vec2 = np.array(VEC2)

# Insert code
math.dist(vec1, vec2)

2.27642738170527

Given two matrices of appropriate dimensions, print their matrix product.


In [63]:
A = [[0.6583596987271446, 1.0128241391924433],
        [0.37783705753739877, 0.42421340135829255]]

B = [[0.6583596987271446, 1.0128241391924433],
        [0.37883705753739877, 0.42421340135829255]]

a = np.array(A)
b = np.array(B)

# Insert code
print(np.dot(a,b))

[[0.81713281 1.09645617]
 [0.40946045 0.5626395 ]]


Given `start` and `end` integer values, create a 1-d array consisting of all integer values between `start` and `end` (inclusive).

In [70]:
start = 3
end = 10

# Insert code
np.array(range(3,11))

array([ 3,  4,  5,  6,  7,  8,  9, 10])

Given a vector of integer data, print all the entries that are even.


In [71]:
VEC = [-3, 5, 1, 2, 18, 2, 234, 11]

vec = np.array(VEC)

# Insert code
print(vec[vec%2==0])

[  2  18   2 234]


Given two matrices, print whether they are equal (i.e. all their corresponding entries are the same).


In [73]:
A = [[0.6583596987271446, 1.0128241391924433],
        [0.37783705753739877, 0.42421340135829255],
        [-0.6905233695318467, -0.498554227530507]]
B = [[0.6583596987271446, 1.0128241391924433],
        [0.37883705753739877, 0.42421340135829255],
        [-0.6905233695318467, -0.498554227530507]]
 
a = np.array(A)
b = np.array(B)

#Insert code
result = np.all(a == b)
if result:
    print('True')
else:
    print('False')


False


Given two vectors of data, print the cosine distance between them.


In [40]:
VEC1 = [-0.25560104,  0.06393334, -0.43760861,  0.35258494, -0.06174621]
VEC2 = [ 0.16257878, -0.88344182,  1.14405499,  0.33765161,  1.206262]

vec1 = np.array(VEC1)
vec2 = np.array(VEC2)

# Insert code 
from numpy.linalg import norm
cosine = np.dot(vec1,vec2)/(norm(vec1)*norm(vec2))
cosine_distance = 1 - cosine
print(cosine_distance)

1.462795581665218


Given a vector of data, scale (multiply) all the entries in the vector by the vector mean and print the result.

In [82]:
VEC = [-0.25560104,  0.06393334, -0.43760861,  0.35258494, -0.06174621]

vec = np.array(VEC)

# Insert code
vec_mean = vec.mean()
print(vec_mean)

np.multiply(vec, vec_mean)

-0.06768751600000002


array([ 0.017301  , -0.00432749,  0.02962064, -0.0238656 ,  0.00417945])

Given a matrix, subtract the column mean from each entry. This has the effect of zero-centering the data and is often done in algorithms such as principal components analysis or when running computer vision models.

In [83]:
A = [[0.6583596987271446, 1.0128241391924433],
       [0.37783705753739877, 0.42421340135829255],
       [-0.6905233695318467, -0.498554227530507]]

a = np.array(A)

# Insert code
b = a - a.mean(axis=1, keepdims=True)
print(b)


[[-0.17723222  0.17723222]
 [-0.02318817  0.02318817]
 [-0.09598457  0.09598457]]


Given a vector of data, compute the softmax scores of the vector.



In [86]:
VEC = [-0.25560104,  0.06393334, -0.43760861,  0.35258494, -0.06174621]

vec = np.array(VEC)

# Insert code
softmax(vec)
    

array([0.1597164 , 0.21984751, 0.1331388 , 0.29341434, 0.19388295])

Given a matrix, print whether or not there are any NaN values in the matrix. 

In [89]:
A = [[0.6583596987271446, 1.0128241391924433],
        [0.37783705753739877, float("nan")],
        [-0.6905233695318467, -0.498554227530507]]

a = np.array(A)
np.isnan(a)


array([[False, False],
       [False,  True],
       [False, False]])

Given a vector of data, normalize the vector to have 0 mean and variance of 1. (Z-score normalization)]

In [90]:
VEC = [-0.25560104,  0.06393334, -0.43760861,  0.35258494, -0.06174621]

vec = np.array(VEC)

# Insert code
print((vec -np.min(vec))/(np.max(vec) - np.min(vec)))

[0.2303329  0.63470772 0.         1.         0.47565865]
